// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const getEnv = (key: string): string => {
  const env = import.meta.env as Record<string, string | undefined>;
  return (env[key] || '').trim();
};

const SUPABASE_URL = getEnv('VITE_SUPABASE_URL');
const SUPABASE_PUBLISHABLE_KEY =
  getEnv('VITE_SUPABASE_PUBLISHABLE_KEY') ||
  getEnv('VITE_SUPABASE_ANON_KEY');

const missingSupabaseVars: string[] = [];
if (!SUPABASE_URL) missingSupabaseVars.push('VITE_SUPABASE_URL');
if (!SUPABASE_PUBLISHABLE_KEY) missingSupabaseVars.push('VITE_SUPABASE_PUBLISHABLE_KEY');

if (missingSupabaseVars.length > 0) {
  console.error(
    `[Supabase] Missing required config entries: ${missingSupabaseVars.join(', ')}. ` +
      'Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in environment variables.'
  );
}

const finalUrl = SUPABASE_URL || 'https://placeholder.supabase.co';
const finalKey = SUPABASE_PUBLISHABLE_KEY || 'placeholder.key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(finalUrl, finalKey, {
  auth: {
    // StudyShare uses Firebase Auth for browser sessions. Keep the Supabase client stateless
    // so it never persists tokens into localStorage where an XSS issue could exfiltrate them.
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
  },
});
