// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const getEnv = (key: string): string => {
  const env = import.meta.env as Record<string, string | undefined>;
  return (env[key] || '').trim();
};

const rawSupabaseUrl = getEnv('VITE_SUPABASE_URL');
const rawSupabaseKey = getEnv('VITE_SUPABASE_PUBLISHABLE_KEY') || getEnv('VITE_SUPABASE_ANON_KEY');

const missingSupabaseVars: string[] = [];
if (!rawSupabaseUrl) missingSupabaseVars.push('VITE_SUPABASE_URL');
if (!rawSupabaseKey) missingSupabaseVars.push('VITE_SUPABASE_PUBLISHABLE_KEY');

const strictEnvCheck = getEnv('VITE_STRICT_ENV_CHECK').toLowerCase() === 'true';

if (missingSupabaseVars.length > 0) {
  const message =
    `[Supabase] Missing env config entries: ${missingSupabaseVars.join(', ')}. ` +
    'Falling back to configured defaults.';

  if (import.meta.env.MODE === 'production') {
    if (strictEnvCheck) {
      throw new Error(`[Supabase] Missing required env vars in production: ${missingSupabaseVars.join(', ')}`);
    }
    console.error(message);
  } else {
    console.warn(message);
  }
}

// Development-only fallback defaults (do not use in production!)
const DEV_FALLBACK_URL = 'https://iayuwsvguwfqjgjsvjiy.supabase.co';
const DEV_FALLBACK_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlheXV3c3ZndXdmcWpnanN2aml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYwNTE5MTEsImV4cCI6MjA4MTYyNzkxMX0.EQhiq-yv9QLBNL_kmT5P59AZPykQkEZwbNbilxquYOA';

const SUPABASE_URL = rawSupabaseUrl || DEV_FALLBACK_URL;
const SUPABASE_PUBLISHABLE_KEY = rawSupabaseKey || DEV_FALLBACK_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // StudyShare uses Firebase Auth for browser sessions. Keep the Supabase client stateless
    // so it never persists tokens into localStorage where an XSS issue could exfiltrate them.
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
  },
});
